=head1 NAME

Web::DOM::AtomPublishedElement - The DOM |AtomPublishedElement| object

=head1 DESCRIPTION

The C<Web::DOM::AtomPublishedElement> class implements the DOM
C<AtomPublishedElement> interface.  The class is used by the Atom
C<published> element.

=head1 METHODS

The methods for classes L<Web::DOM::Element>,
L<Web::DOM::AtomElement>, and L<Web::DOM::AtomDateConstruct> are
available.

=head1 SPECIFICATION

=over 4

=item ATOMDOM

Atom DOM <http://suika.suikawiki.org/www/markup/xml/atomdom>.

=back

=head1 SEE ALSO

L<Web::DOM::AtomElement>, L<Web::DOM::AtomDateConstruct>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
