=head1 NAME

Web::DOM::AtomCategoryElement - The DOM |AtomCategoryElement| object

=head1 DESCRIPTION

The C<Web::DOM::AtomCategoryElement> class implements the DOM
C<AtomCategoryElement> interface.  The class is used by the Atom
C<category> element.

=head1 METHODS

In addition to the methods available for classes L<Web::DOM::Element>
and L<Web::DOM::AtomElement>, the following method is available:

=over 4

=item $string = $el->label

=item $el->label ($string)

Return or set the C<label> attribute.  [ATOMDOM]

=item $string = $el->scheme

=item $el->scheme ($string)

Return or set the C<scheme> attribute.  [ATOMDOM]

=item $string = $el->term

=item $el->term ($string)

Return or set the C<term> attribute.  [ATOMDOM]

=back

=head1 SPECIFICATION

=over 4

=item ATOMDOM

Atom DOM <http://suika.suikawiki.org/www/markup/xml/atomdom>.

=back

=head1 SEE ALSO

L<Web::DOM::AtomElement>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
