=head1 NAME

Web::DOM::AtomSourceElement - The DOM |AtomSourceElement| object

=head1 DESCRIPTION

The C<Web::DOM::AtomSourceElement> class implements the DOM
C<AtomSourceElement> interface.  The class is used by the Atom
C<source> element.

=head1 METHODS

In addition to the methods for classes L<Web::DOM::Element> and
L<Web::DOM::AtomElement>, following methods are available:

=over 4

=item $string = $el->atom_id

=item $el->atom_id ($string)

Return or set the value of the C<atom:id> child element.  [ATOMDOM]

=item $col = $el->author_elements

Return a L<Web::DOM::HTMLCollection> containing the C<atom:author>
element childs.  [ATOMDOM]

=item $col = $el->category_elements

Return a L<Web::DOM::HTMLCollection> containing the C<atom:category>
element childs.  [ATOMDOM]

=item $col = $el->contributor_elements

Return a L<Web::DOM::HTMLCollection> containing the
C<atom:contributor> element childs.  [ATOMDOM]

=item $el2 = $el->generator_element

Return the C<atom:generator> element child, if any.  [ATOMDOM]

If the C<manakai-create-child-element> configuration parameter is set
to true and there is no C<atom:generator> element child, a new element
is created and returned.  Otherwise, no element is created and
C<undef> is returned.

=item $url = $el->icon

=item $el->icon ($url)

Return or set the value of the C<atom:icon> child element.  The method
returns the resoloved absolute URL if the value is a relative URL.
[ATOMDOM]

=item $col = $el->link_elements

Return a L<Web::DOM::HTMLCollection> containing the C<atom:link>
element childs.  [ATOMDOM]

=item $url = $el->logo

=item $el->logo ($url)

Return or set the value of the C<atom:logo> child element.  The method
returns the resoloved absolute URL if the value is a relative URL.
[ATOMDOM]

=item $el2 = $el->rights_element

Return the C<atom:rights> element child, if any.  [ATOMDOM]

If the C<manakai-create-child-element> configuration parameter is set
to true and there is no C<atom:rights> element child, a new element is
created and returned.  Otherwise, no element is created and C<undef>
is returned.

=item $el2 = $el->subtitle_element

Return the C<atom:subtitle> element child, if any.  [ATOMDOM]

If the C<manakai-create-child-element> configuration parameter is set
to true and there is no C<atom:subtitle> element child, a new element
is created and returned.  Otherwise, no element is created and
C<undef> is returned.

=item $el2 = $el->title_element

Return the C<atom:title> element child, if any.  [ATOMDOM]

If the C<manakai-create-child-element> configuration parameter is set
to true and there is no C<atom:title> element child, a new element is
created and returned.  Otherwise, no element is created and C<undef>
is returned.

=item $el2 = $el->updated_element

Return the C<atom:updated> element child, if any.  [ATOMDOM]

If the C<manakai-create-child-element> configuration parameter is set
to true and there is no C<atom:updated> element child, a new element
is created and returned.  Otherwise, no element is created and
C<undef> is returned.

=back

=head1 SPECIFICATION

=over 4

=item ATOMDOM

Atom DOM <http://suika.suikawiki.org/www/markup/xml/atomdom>.

=back

=head1 SEE ALSO

L<Web::DOM::AtomElement>, L<Web::DOM::AtomFeedElement>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
