=head1 NAME

Web::DOM::CSSGroupingRule - The DOM |CSSGroupingRule| object

=head1 DESCRIPTION

The C<Web::DOM::CSSGroupingRule> class implements the DOM
C<CSSGroupingRule> interface.

=head1 METHODS

In addition to the methods of the L<Web::DOM::CSSRule> class,
following methods are available:

=over 4

=item $list = $rule->css_rules

Return the L<Web::DOM::CSSRuleList> object containing the CSS rules in
the rule.  [CSSOM]

=item $rule->delete_rule ($index)

Return a rule from the list of rules contained by the rule.  [CSSOM]

=item $index = $rule->insert_rule ($string, $index)

Parse the string as a CSS rule and insert into the specified index of
the list of rules contained by the rule.  [CSSOM]

=back

Any C<CSSGroupingRule> object is an instance of one of its subclasses.
For example, a C<CSSGroupingRule> object whose C<type> is
C<MEDIA_RULE> is an instance of L<Web::DOM::CSSMediaRule>.  There is
the following subclass:

L<Web::DOM::CSSMediaRule>.

=head1 DEPENDENCY

See L<Web::DOM/DEPENDENCY>.

=head1 SPECIFICATION

=over 4

=item CSSOM

CSSOM <http://dev.w3.org/csswg/cssom/>.

=back

=head1 SEE ALSO

L<Web::DOM::CSSRule>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2012-2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
