=head1 NAME

Web::DOM::Exception - DOM |DOMException| object

=head1 DESCRIPTION

The C<Web::DOM::Exception> class implements the DOM C<DOMException>
interface.

=head1 METHODS

In addition to the methods of the class C<Web::DOM::Error>, the
following method is available:

=over 4

=item $code = $error->code

Return the error code.  This method is considered depreacated and the
C<name> method should be used instead.  [DOM]

=back

=head1 CONSTANTS

This class exports several constants for error codes, but they are now
deprecated in favor of the C<name> method returning string error names
(see L<Web::DOM::Error>).

=head1 SPECIFICATION

=over 4

=item DOM

DOM Standard <http://dom.spec.whatwg.org/>.

=back

=head1 SEE ALSO

L<Web::DOM::Error>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2012-2014 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
