=head1 NAME

Web::DOM::Exception - |DOMException| object

=head1 DESCRIPTION

The C<Web::DOM::Exception> class implements the C<DOMException>
interface.

=head1 METHODS

In addition to the methods of the class L<Web::DOM::Error>, a
deprecated method C<code> is available.  [DOM]

An instance of the C<Web::DOM::Exception> class is implementing the
Perl Error Object Interface Level 1 (see L<Web::DOM::Error/ERROR
OBJECT API>).

=head1 CONSTANTS

This class exports several constants for error codes for the C<code>
method, but they are now deprecated in favor of the C<name> method.

=head1 SPECIFICATION

=over 4

=item WEBIDL

Web IDL <https://heycam.github.io/webidl/>.

=back

=head1 SEE ALSO

L<Web::DOM::Error>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2012-2017 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
