=head1 NAME

Web::DOM::HTMLLinkElement - The DOM |HTMLLinkElement| object

=head1 DESCRIPTION

The C<Web::DOM::HTMLLinkElement> class implements the DOM
C<HTMLLinkElement> interface.  The class is used by the HTML C<link>
element.

=head1 METHODS

In addition to the methods available for classes L<Web::DOM::Element>
and L<Web::DOM::HTMLElement>, the following method is available:

=over 4

=item $string = $el->crossorigin

=item $el->crossorigin ($string)

Return or set the C<crossorigin> attribute.  [HTML]

=item $string = $el->hreflang

=item $el->hreflang ($string)

Return or set the C<hreflang> attribute.  [HTML]

=item $string = $el->media

=item $el->media ($string)

Return or set the C<media> attribute.  [HTML]

=item $string = $el->rel

=item $el->rel ($string)

Return or set the C<rel> attribute.  [HTML]

=item $string = $el->type

=item $el->type ($string)

Return or set the C<type> attribute.  [HTML]

=back

=head1 SPECIFICATION

=over 4

=item HTML

HTML Standard
<http://www.whatwg.org/specs/web-apps/current-work/#link>.

=back

=head1 SEE ALSO

L<Web::DOM::HTMLElement>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
