=head1 NAME

Web::DOM::HTMLMenuElement - DOM |HTMLMenuElement| object

=head1 DESCRIPTION

The C<Web::DOM::HTMLMenuElement> class implements the DOM
C<HTMLMenuElement> interface.  This class is used by the HTML C<menu>
element.

=head1 METHODS

In addition to the methods available for classes L<Web::DOM::Element>
and L<Web::DOM::HTMLElement>, obsolete C<compact> method is available.
[HTML]

=head1 SPECIFICATION

=over 4

=item HTML

HTML Standard <https://html.spec.whatwg.org/>.

=back

=head1 SEE ALSO

L<Web::DOM::HTMLElement>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013-2017 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
