=head1 NAME

Web::DOM::HTMLTableElement - The DOM |HTMLTableElement| object

=head1 DESCRIPTION

The C<Web::DOM::HTMLTableElement> class implements the DOM
C<HTMLTableElement> interface.  The class is used by the HTML C<table>
element.

=head1 METHODS

In addition to the methods available for classes L<Web::DOM::Element>
and L<Web::DOM::HTMLElement>, the following methods are available:

=over 4

=item $caption = $el->caption

=item $el->caption ($caption)

Return or set the C<caption> element for the table.  [HTML]

=item $caption = $el->create_caption

Return the C<caption> element for the table.  If the table does not
contain the C<caption> element, a new element is created and returned.
[HTML]

=item $el->delete_caption

Remove the C<caption> element from the table, if any.  [HTML]

=item $boolean = $el->sortable

=item $el->sortable ($boolean)

Return or set whether the C<sortable> attribute is specified or not.
[HTML]

=back

Additionally, the following obsolete methods are available: C<align>,
C<bgcolor>, C<border>, C<cellpadding>, C<cellspacing>, C<frame>,
C<summary>, C<rules>, and C<width>.  [HTML]

=head1 SPECIFICATION

=over 4

=item HTML

HTML Standard
<http://www.whatwg.org/specs/web-apps/current-work/#the-table-element>.

=back

=head1 SEE ALSO

L<Web::DOM::HTMLElement>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
