=head1 NAME

Web::DOM::HTMLMenuItemElement - DOM |HTMLMenuItemElement| object

=head1 DESCRIPTION

This class and interface are obsolete.  See L<Web::DOM::HTMLElement>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013-2017 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
