=head1 NAME

Web::DOM::HTMLAllCollection - The DOM |HTMLAllCollection| object

=head1 DESCRIPTION

The C<Web::DOM::HTMLAllCollection> class implements the DOM
C<HTMLAllCollection> interface.

=head1 METHODS

Following methods are available:

=over 4

=item $node = $col->[$index]

=item $node = $col->{$index}

=item $node = $col->item ($index)

Return the node in the collection, specified by its index.  [DOM]
[HTML] [DOMPERL]

Use of the C<item> method is discouraged as it doesn't support
Perl-ish ways to access items, such as negative indexing, while C<<
$col->[-1] >> works as intended.

=item $obj = $col->{$key}

=item $obj = $col->item ($key)

=item $obj = $col->named_item ($key)

Return the node whose ID or the C<name> attribute is equal to the
argument, if any, or C<undef>.  If there are multiple elements with
same ID or C<name>, another L<Web::DOM::HTMLCollection> containing
them is returned instead.  [DOM] [HTML] [DOMPERL]

=back

=head1 SPECIFICATIONS

=over 4

=item DOM

DOM Living Standard
<http://dom.spec.whatwg.org/#interface-htmlcollection>.

=item HTML

HTML Living Standard
<http://www.whatwg.org/specs/web-apps/current-work/#htmlallcollection>.

=item DOMPERL

manakai's DOM Perl Binding
<http://suika.fam.cx/~wakaba/wiki/sw/n/manakai%27s%20DOM%20Perl%20Binding>.

=back

=head1 SEE ALSO

L<Web::DOM::HTMLCollection>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2012-2015 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
