=head1 NAME

Web::DOM::HTMLEmbedElement - The DOM |HTMLEmbedElement| embed

=head1 DESCRIPTION

The C<Web::DOM::HTMLEmbedElement> class implements the DOM
C<HTMLEmbedElement> interface.  The class is used by the HTML
C<embed> element.

=head1 METHODS

In addition to the methods available for classes L<Web::DOM::Element>
and L<Web::DOM::HTMLElement>, the following methods are available:

=over 4

=item $string = $el->height

=item $el->height ($string)

Return or set the C<height> attribute.  [HTML]

=item $string = $el->type

=item $el->type ($string)

Return or set the C<type> attribute.  [HTML]

=item $string = $el->width

=item $el->width ($string)

Return or set the C<width> attribute.  [HTML]

=back

Additionally, obsolete methods C<align> and C<name> are available.
[HTML]

=head1 SPECIFICATION

=over 4

=item HTML

HTML Standard
<http://www.whatwg.org/specs/web-apps/current-work/#the-embed-element>.

=back

=head1 SEE ALSO

L<Web::DOM::HTMLElement>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
