=head1 NAME

Web::DOM::HTMLIFrameElement - The DOM |HTMLIFrameElement| object

=head1 DESCRIPTION

The C<Web::DOM::HTMLIFrameElement> class implements the DOM
C<HTMLIFrameElement> interface.  The class is used by the HTML
C<iframe> element.

=head1 METHODS

In addition to the methods available for classes L<Web::DOM::Element>
and L<Web::DOM::HTMLElement>, the following methods are available:

=over 4

=item $boolean = $el->allowfullscreen

=item $el->allowfullscreen ($boolean)

Return or set whether the C<allowfullscreen> attribute is specified or
not.  [HTML]

=item $string = $el->height

=item $el->height ($string)

Return or set the C<height> attribute.  [HTML]

=item $string = $el->name

=item $el->name ($string)

Return or set the C<name> attribute.  [HTML]

=item $tokens = $el->sandbox

=item $el->sandbox ($string)

Return the L<Web::DOM::SettableTokenList> object for the C<sandbox>
attribute, or set the C<sandbox> attribute to the specified string
value.  [HTML]

=item $boolean = $el->seamless

=item $el->seamless ($boolean)

Return or set whether the C<seamless> attribute is specified or not.
[HTML]

=item $string = $el->src

=item $el->src ($string)

Return or set the C<src> attribute.  [HTML]

=item $string = $el->srcdoc

=item $el->srcdoc ($string)

Return or set the C<srcdoc> attribute.  [HTML]

=item $string = $el->width

=item $el->width ($string)

Return or set the C<width> attribute.  [HTML]

=back

Additionally, the following obsolete methods are available: C<align>,
C<frameborder>, C<longdesc>, C<marginheight>, C<marginwidth>, and
C<scrolling>.  [HTML]

=head1 SPECIFICATION

=over 4

=item HTML

HTML Standard
<http://www.whatwg.org/specs/web-apps/current-work/#the-iframe-element>.

=back

=head1 SEE ALSO

L<Web::DOM::HTMLElement>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
