=head1 NAME

Web::DOM::HTMLTableColElement - The DOM |HTMLTableColElement| object

=head1 DESCRIPTION

The C<Web::DOM::HTMLTableColElement> class implements the DOM
C<HTMLTableColElement> interface.  The class is used by the HTML
C<colgroup> and C<col> elements.

=head1 METHODS

In addition to the methods available for classes L<Web::DOM::Element>
and L<Web::DOM::HTMLElement>, the following method is available:

=over 4

=item $integer = $el->span

=item $el->span ($integer)

Return or set the C<span> attribute.  [HTML]

=back

Additionally, the following obsolete methods are available: C<align>,
C<ch>, C<ch_off>, C<valign>, and C<width>.  [HTML]

=head1 SPECIFICATION

=over 4

=item HTML

HTML Standard
<http://www.whatwg.org/specs/web-apps/current-work/#the-colgroup-element>.

=back

=head1 SEE ALSO

L<Web::DOM::HTMLElement>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
