=head1 NAME

Web::DOM::HTMLModElement - The DOM |HTMLModElement| object

=head1 DESCRIPTION

The C<Web::DOM::HTMLModElement> class implements the DOM
C<HTMLModElement> interface.  The class is used by the HTML C<ins> and
C<del> elements.

=head1 METHODS

In addition to the methods available for classes L<Web::DOM::Element>
and L<Web::DOM::HTMLElement>, following methods are available:

=over 4

=item $string = $el->cite

=item $el->cite ($string)

Return or set the C<cite> attribute.  [HTML]

=item $string = $el->datetime

=item $el->datetime ($string)

Return or set the C<datetime> attribute.  [HTML]

=back

=head1 SPECIFICATION

=over 4

=item HTML

HTML Standard
<http://www.whatwg.org/specs/web-apps/current-work/#edits>.

=back

=head1 SEE ALSO

L<Web::DOM::HTMLElement>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
