=head1 NAME

Web::DOM::HTMLLIElement - The DOM |HTMLLIElement| object

=head1 DESCRIPTION

The C<Web::DOM::HTMLLIElement> class implements the DOM
C<HTMLLIElement> interface.  The class is used by the HTML C<li>
element.

=head1 METHODS

In addition to the methods available for classes L<Web::DOM::Element>
and L<Web::DOM::HTMLElement>, the following method is available:

=over 4

=item $integer = $el->value

=item $el->value ($integer)

Return or set the C<value> attribute.  [HTML]

=back

Additionally, the obsolete C<type> method is available.  [HTML]

=head1 SPECIFICATION

=over 4

=item HTML

HTML Standard
<http://www.whatwg.org/specs/web-apps/current-work/#the-script-element>.

=back

=head1 SEE ALSO

L<Web::DOM::HTMLElement>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
