=head1 NAME

Web::DOM::HTMLOListElement - The DOM |HTMLOListElement| object

=head1 DESCRIPTION

The C<Web::DOM::HTMLOListElement> class implements the DOM
C<HTMLOListElement> interface.  The class is used by the HTML C<ol>
element.

=head1 METHODS

In addition to the methods available for classes L<Web::DOM::Element>
and L<Web::DOM::HTMLElement>, the following methods are available:

=over 4

=item $boolean = $el->reversed

=item $el->reversed ($boolean)

Return or set whether the C<reversed> attribute is specified or not.
[HTML]

=item $string = $el->type

=item $el->type ($string)

Return or set the C<type> attribute.  [HTML]

=back

Additionally, the obsolete C<compact> method is available.  [HTML]

=head1 SPECIFICATION

=over 4

=item HTML

HTML Standard
<http://www.whatwg.org/specs/web-apps/current-work/#the-script-element>.

=back

=head1 SEE ALSO

L<Web::DOM::HTMLElement>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
