=head1 NAME

Web::DOM::HTMLFontElement - The DOM |HTMLFontElement| object

=head1 DESCRIPTION

The C<Web::DOM::HTMLFontElement> class implements the DOM
C<HTMLFontElement> interface.  The class is used by the HTML C<font>
element.

The interface, as well as the C<font> element, is obsolete.

=head1 METHODS

In addition to the methods available for classes L<Web::DOM::Element>
and L<Web::DOM::HTMLElement>, the following methods are available:
C<color>, C<face>, and C<size>.  [HTML]

=head1 SPECIFICATION

=over 4

=item HTML

HTML Standard
<http://www.whatwg.org/specs/web-apps/current-work/#htmlfontelement>.

=back

=head1 SEE ALSO

L<Web::DOM::HTMLElement>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
