=head1 NAME

Web::DOM::HTMLAppletElement - DOM |HTMLAppletElement| object

=head1 DESCRIPTION

The C<Web::DOM::HTMLAppletElement> class implements the DOM
C<HTMLAppletElement> interface.  The class is used by the HTML
C<applet> element.

The interface, as well as the C<applet> element, is obsolete.  Though
this interface has been removed from the HTML Standard in 2017, it is
still included in this implementation for API compatibility.  (A Perl
DOM module has different compatibility requirements from Web browser
DOM API implementations.)

=head1 METHODS

In addition to the methods available for classes L<Web::DOM::Element>
and L<Web::DOM::HTMLElement>, the following obsolete methods are
available: C<align>, C<alt>, C<archive>, C<codebase>, C<height>,
C<hspace>, C<name>, C<object>, C<vspace>, and C<width>.  [HTML]

=head1 SPECIFICATION

=over 4

=item HTML

HTML Standard (until August 2017)
<https://github.com/whatwg/html/commit/b9b9d60f9451c05f8e8d542e4094f987ae1a5fb8>.

=back

=head1 SEE ALSO

L<Web::DOM::HTMLElement>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013-2017 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
