=head1 NAME

Web::DOM::HTMLTableRowElement - The DOM |HTMLTableRowElement| object

=head1 DESCRIPTION

The C<Web::DOM::HTMLTableRowElement> class implements the DOM
C<HTMLTableRowElement> interface.  The class is used by the HTML C<tr>
element.

=head1 METHODS

In addition to the methods available for classes L<Web::DOM::Element>
and L<Web::DOM::HTMLElement>, the following method is available:

=over 4

XXX

=back

Additionally, the following obsolete methods are available: C<align>,
C<bgcolor>, C<ch>, C<ch_off>, and C<valign>.  [HTML]

=head1 SPECIFICATION

=over 4

=item HTML

HTML Standard
<http://www.whatwg.org/specs/web-apps/current-work/#the-tr-element>.

=back

=head1 SEE ALSO

L<Web::DOM::HTMLElement>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
