=head1 NAME

Web::DOM::ProcessingInstruction - The DOM |ProcessingInstruction| object

=head1 DESCRIPTION

The C<Web::DOM::ProcessingInstruction> class implements the DOM
C<ProcessingInstruction> interface.  It represents a processing
instruction.

=head1 METHODS

In addition to the methods of classes L<Web::DOM::Node>,
L<Web::DOM::CharacterData>, and L<Web::DOM::ChildNode>, the following
method is available:

=over 4

=item $name = $pi->target

Return the target of the processing instruction.

=back

In addition, the obsolete C<manakai_base_uri> method is available.

=head1 SPECIFICATIONS

=over 4

=item DOM

DOM Living Standard
<http://dom.spec.whatwg.org/#interface-processinginstruction>.

=item MANAKAI

manakai DOM Extensions
<http://suika.suikawiki.org/~wakaba/wiki/sw/n/manakai++DOM%20Extensions>.

=back

=head1 SEE ALSO

L<Web::DOM::Node>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2012-2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
