=head1 NAME

Web::DOM::SettableTokenList - The DOM |DOMSettableTokenList| object

=head1 DESCRIPTION

The C<Web::DOM::SettableTokenList> class implements the DOM
C<DOMSettableTokenList> interface.

The C<DOMSettableTokenList> object is used by, e.g., HTML C<sandbox>,
C<dropzone>, and C<headers> attributes.

=head1 METHODS

In addition to the methods available for the class
L<Web::DOM::TokenList>, the followinig method is available:

=over 4

=item $string = $tokens->value

Return the serialized representation of the tokens, joined by the
space character.  [DOM]

=item $tokens->value ($string)

Replace the tokens in the list by the tokens specified as the
space-separeted list.  [DOM]

=back

=head1 SPECIFICATION

=over 4

=item DOM

DOM Living Standard <http://dom.spec.whatwg.org/>.

=back

=head1 SEE ALSO

L<Web::DOM::Element>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
