=head1 NAME

Web::DOM::TypeError - |TypeError| object

=head1 DESCRIPTION

A C<Web::DOM::TypeError> object is intended to be equivalent to
JavaScript C<TypeError>.

=head1 METHODS

In addition to the methods of the L<Web::DOM:Error>, following method
is available:

=over 4

=item $error = Web::DOM::TypeError->new ($message)

Create and return a new type error object.

If a character string is specified as an argument, the error's
C<message> is set to the argument.  Otherwise, the C<message> is set
to the empty string.

=back

=head1 SPECIFICATION

=over 4

=item WEBIDL

WebIDL <https://heycam.github.io/webidl/>.

=back

=head1 SEE ALSO

L<Web::DOM::TypeError>.

ECMAScript C<TypeError>
<https://tc39.github.io/ecma262/#sec-native-error-types-used-in-this-standard-typeerror>.

Web IDL C<TypeError>
<https://heycam.github.io/webidl/#exceptiondef-typeerror>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2012-2017 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
