=head1 NAME

Web::DOM::WheelEvent - The DOM |WheelEvent| object

=head1 DESCRIPTION

The C<Web::DOM::WheelEvent> class implements the DOM C<WheelEvent>
interface.

=head1 METHODS

In addition to the methods of the L<Web::DOM::Event>,
L<Web::DOM::UIEvent>, and L<Web::DOM::MouseEvent> classes, following
methods are available:

=over 4

=item $int = $ev->delta_mode

Return the scroll delta mode.  [DOM3EVENTS]

=item $number = $ev->delta_x

=item $number = $ev->delta_y

=item $number = $ev->delta_z

Return the amount of the delta.  [DOM3EVENTS]

=back

The C<new> method of the L<Web::DOM::RelatedEvent> class accepts the
C<delta_mode>, C<delta_x>, C<delta_y>, and C<delta_z> name/value pairs
in its second arguments, in addition to the name/value pairs for
L<Web::DOM::Event>, L<Web::DOM::UIEvent>, and L<Web::DOM::MouseEvent>
objects.  [UIEVENTS]

=head1 CONSTANTS

Constants are exported from the L<Web::DOM::WheelEvent> module by
default.  Following constants are used by the C<delta_mode> method
[DOM3EVENTS]:

  DOM_DELTA_PIXEL DOM_DELTA_LINE DOM_DELTA_PAGE

=head1 SPECIFICATIONS

=over 4

=item DOM3EVENTS

DOM Level 3 Events
<http://dev.w3.org/2006/webapi/DOM-Level-3-Events/html/DOM3-Events.html#events-uievents>.

=item UIEVENTS

UI Events
<https://dvcs.w3.org/hg/d4e/raw-file/tip/source_respec.htm#constructor-uievent>.

=back

=head1 SEE ALSO

L<Web::DOM::Event>, L<Web::DOM::UIEvent>, L<Web::DOM::MouseEvent>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
